version: "3.8"
services:
    rmf_office_demo:
        image: steplerchik/open-rmf-web-demo:latest
        network_mode: host
        container_name: rmf_office_demo
        env_file: $ENV_FILE
        environment:
            - NVIDIA_DRIVER_CAPABILITIES=all
            - NVIDIA_VISIBLE_DEVICES=all
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
        tty: true
        runtime: nvidia
        volumes:
            - type: bind
              source: /tmp/.X11-unix
              target: /tmp/.X11-unix
        command: bash -c "ros2 launch rmf_demos_gz office.launch.xml server_uri:='http://localhost:8000/_internal' "
